# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
  - "5.4"
  - "5.5"

# WordPress version used in first build configuration.
env:
  - WP_VERSION=master

# we will build a matrix of PHP to WP_VERSIONs later.
matrix:
  allow_failures:
  - php: hhvm

before_install:
  - composer install
  # - npm install

  # Selenium server
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - sleep 5


install:
  - pwd

  # install codeception
  - wget http://codeception.com/codecept.phar
  - chmod +x codecept.phar
  - sudo mv codecept.phar /usr/local/bin/codecept

  # install Apache
  - sudo apt-get update
  - sudo apt-get install apache2
  - sudo apt-get install php5
  - sudo apt-get install libapache2-mod-php5
  
  # make folder to place website documents in
  - sudo mkdir -p /etc/apache2/sites-available/inboundsoon.dev
  
  # create hosts file for site
  - sudo cp -f tests/build/travis-ci-apache /etc/apache2/sites-available/inboundsoon.dev
  
  # set new hosts file into settings
  - sudo a2ensite inboundsoon.dev  
  
  # create php.conf & php.load file for apache mods
  - sudo cp -f tests/build/php.conf /etc/apache2/mods-available/php.conf
  - sudo cp -f tests/build/php.load /etc/apache2/mods-available/php.load
  
  # enable php
  - sudo a2enmod php
  
  # restart apache
  - sudo service apache2 restart
  - sleep 5

  # Set permissions for root website contents folder & all subfolders
  - sudo chmod -R 755 /var/www
  
  # list contents of apache's sites-available folder to make sure our hosts file was created
  - ls /etc/apache2/sites-available/
  - ls /etc/apache2/mods-available/

before_script:
  # Someone explain to me where PLUGIN_SLUG comes from and what this line does.
  - export PLUGIN_SLUG=$(basename $(pwd))

  # create directory to host wordpress inside inside our /var/www directory
  - sudo mkdir -p /var/www/inboundsoon.dev
  # add current user permissions to our created directory
  - sudo chown -R $USER:$USER /var/www/inboundsoon.dev
  
  # define public/private access permissions for our created directory
  - sudo chmod -R 777 /var/www/inboundsoon.dev
  
  # clone wordpress developer git into our created directory
  - git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /var/www/inboundsoon.dev
  - ls /var/www/
  
  # set the permissions for all newly created files in our created direcotry
  - sudo chmod -R 755 /var/www/inboundsoon.dev

  # change directory into inboundsoon.dev
  - cd /var/www/inboundsoon.dev

  # pull latests inbound plugins
  - git clone --branch="master" https://github.com/inboundnow/cta.git /var/www/inboundsoon.dev/wp-content/plugins/cta
  - git clone --branch="master" https://github.com/inboundnow/leads.git /var/www/inboundsoon.dev/wp-content/plugins/leads


  # make a directory for landing pages
  - mv "/home/travis/build/inboundnow/$PLUGIN_SLUG" "/var/www/inboundsoon.dev/src/wp-content/plugins/$PLUGIN_SLUG"

  # create database
  - mysql -e "CREATE DATABASE wordpress_develop;" -uroot
  - cp wp-tests-config-sample.php wp-tests-config.php

  # setup database for tests config
  - sed -i "s/youremptytestdbnamehere/wordpress_develop/" wp-tests-config.php
  - sed -i "s/yourusernamehere/root/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php
  - sed -i "s/example.com/inboundsoon.dev/" wp-tests-config.php

  # change into plugin directory to make sure our script runs the right tests
  - cd /var/www/inboundsoon.dev/src/wp-content/plugins/$PLUGIN_SLUG



script:
  - phpunit
  #- php codecept run

addons:
  hosts:
    - inboundsoon.dev
  #sauce_connect:
   # username: "hudson-inbound"
   # access_key: "fad20a89-ba7c-4797-b2e2-a13309885479"