# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
  - "5.4"
  - "5.5"

# WordPress version used in first build configuration.
env:
  - WP_VERSION=master

# we will build a matrix of PHP to WP_VERSIONs later. 
matrix:
  allow_failures:
  - php: hhvm

before_install: 
  - composer install
  # - npm install
  
  # Selenium server
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - sleep 5
  
  
install:
  # install codeception 
  - wget http://codeception.com/codecept.phar
  - chmod +x codecept.phar
  - sudo mv codecept.phar /usr/local/bin/codecept
  
  # install Apache  
  - sudo apt-get update
  - sudo apt-get install apache2
 
  - sudo service apache2 restart
  - ls 
  - ls /etc/
  - ls /etc/apache2
  - ls /etc/apache2/sites-available/
  
    #setup virtual hosts from travis-ci-apache file template

  - sudo cp -f tests/build/travis-ci-apache /etc/apache2/sites-available/default

before_script: 
  - ps ax
  - netstat -nl
  
  #setup virtual hosts from travis-ci-apache file template
  - ps ax
  - sudo service apache2 start
  - netstat -nl
  - ls 
  - ls /etc/
  - ls /etc/apache2
  - ls /etc/apache2/sites-available/
  - sudo cp -f tests/build/travis-ci-apache /etc/apache2/sites-available/default

  
  - export PLUGIN_SLUG=$(basename $(pwd)) 
  
  # isntall wordpress
  - git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress

  # pull latests inbound plugins
  - git clone --branch="master" https://github.com/inboundnow/cta.git /tmp/wordpress/wp-content/plugins/cta
  - git clone --branch="master" https://github.com/inboundnow/leads.git /tmp/wordpress/wp-content/plugins/leads

  # drop back a directory
  - cd ..
  
  # make a directory for landing pages
  - mv "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
  - cd /tmp/wordpress
  
  # create database
  - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
  - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php
  - cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
  - ls -l
  

script: 
  - phpunit
  #- php codecept run
  
addons:
  hosts:
    - inboundsoon.dev
  #sauce_connect:
   # username: "hudson-inbound"
   # access_key: "fad20a89-ba7c-4797-b2e2-a13309885479"