# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
  - "5.4"
  - "5.5"

# WordPress version used in first build configuration.
env:
  - WP_VERSION=master

# we will build a matrix of PHP to WP_VERSIONs later. 
matrix:
  allow_failures:
  - php: hhvm

before_install: 
  - composer install
  # - npm install
  
  # Selenium server
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - sleep 5
  
  
install:
  - ls 
  - ls ../
  - ls ../../
  - ls ../../../
  - ls ../../../../
  - ls ../../../../../
  
  
  # install codeception 
  - wget http://codeception.com/codecept.phar
  - chmod +x codecept.phar
  - sudo mv codecept.phar /usr/local/bin/codecept
  
  # install Apache  
  - sudo apt-get update
  - sudo apt-get install apache2 
  - sudo mkdir -p /etc/apache2/sites-available/example.com
  - sudo cp -f tests/build/travis-ci-apache /etc/apache2/sites-available/example.com
  - sudo chmod -R 755 /var/www
  - sudo service apache2 restart
  - sudo a2ensite example.com
  - sleep 5	
  
  
  - ls /etc/apache2/sites-available/  

before_script: 
  # Someone explain to me where PLUGIN_SLUG comes from and what this line does.
  - export PLUGIN_SLUG=$(basename $(pwd))  
  
  # install wordpress
  - sudo mkdir -p /var/www/example.com  
  - sudo chown -R $USER:$USER /var/www/example.com
  - sudo chmod -R 777 /var/www/example.com
  - git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /var/www/example.com
  - ls /var/www/  
  - sudo chmod -R 777 /var/www/example.com
  

  # pull latests inbound plugins
  - git clone --branch="master" https://github.com/inboundnow/cta.git /var/www/example.com/wp-content/plugins/cta
  - git clone --branch="master" https://github.com/inboundnow/leads.git /var/www/example.com/wp-content/plugins/leads

  
  # make a directory for landing pages
  - mv "$PLUGIN_SLUG" "/var/www/example.com/src/wp-content/plugins/$PLUGIN_SLUG"
  
  # create database
  - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/word press_tests/" wp-tests-config.php
  - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php
  - cd "/var/www/example.com/src/wp-content/plugins/$PLUGIN_SLUG"
  - ls -l
  

script: 
  - phpunit
  #- php codecept run
  
addons:
  hosts:
    - example.com
  #sauce_connect:
   # username: "hudson-inbound"
   # access_key: "fad20a89-ba7c-4797-b2e2-a13309885479"