# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - "5.4"
    - "5.5"
    - "5.6"

# WordPress version used in first build configuration.
env:
    - WP_VERSION=master

# Next we define our matrix of additional build configurations to test against.
# The versions listed above will automatically create our first configuration,
# so it doesn't need to be re-defined below.

# WP_VERSION specifies the tag to use. The way these tests are configured to run
# requires at least WordPress 3.8. Specify "master" to test against SVN trunk.

# Note that Travis CI supports listing these above to automatically build a
# matrix of configurations, but we're being nice here by manually building a
# total of four configurations even though we're testing 4 versions of PHP
# along with 2 versions of WordPress (which would build 8 configs otherwise).
# This takes half as long to run while still providing adequate coverage.

matrix:
  allow_failures:
    - php: hhvm

services:
  - rabbitmq
  - mongodb

install:
  # install codeception 
  - wget http://codeception.com/codecept.phar
  - chmod +x codecept.phar
  - sudo mv codecept.phar /usr/local/bin/codecept

  - /home/travis/.phpenv/versions/5.5/bin/composer self-update
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer global require "fxp/composer-asset-plugin:1.0.0"
  - composer self-update
  - composer install --prefer-dist
  # Queue (Beanstalkd)
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  # Yii2
  - composer create-project yiisoft/yii2-app-basic frameworks-yii-basic
  # Phalcon
  - 'git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b 1.2.4'
  - '[[ "$TRAVIS_PHP_VERSION" == "hhvm" ]] || [[ "$TRAVIS_PHP_VERSION" == "5.6" ]] || (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize &> /dev/null && ./configure --enable-phalcon  &> /dev/null && make -j4 && sudo make install && phpenv config-add ../unit-tests/ci/phalcon.ini &> /dev/null && cd ../..;)'
  - 'git clone -q --depth=1 https://github.com/DavertMik/forum.git frameworks-phalcon'
  # Laravel 4
  - git clone -q https://github.com/Codeception/sample-l4-app.git frameworks-laravel
  - composer install -d frameworks-laravel --no-dev  --prefer-dist
  # Laravel 5
  - git clone -q https://github.com/janhenkgerritsen/codeception-laravel5-sample.git frameworks-l5
  - composer install -d frameworks-l5 --no-dev  --prefer-dist
  # Symfony
  - git clone https://github.com/DavertMik/SymfonyCodeceptionApp.git frameworks-symfony
  - composer install -d frameworks-symfony --no-dev  --prefer-dist
  

# Clones WordPress and configures our testing environment.
before_script:
    - beanstalkd -d -l 127.0.0.1 -p 11300
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - java -jar selenium-server-standalone-2.42.2.jar -port 4444 > /dev/null &
    - sleep 5
    - php -S localhost:8000 -t tests/data/app &
    - php -S localhost:8010 -t tests/data &
    # Phalcon
    - "mysql -e 'CREATE DATABASE forum;'"
    - cat frameworks-phalcon/schemas/forum.sql | mysql forum
    # Laravel 4
    - touch frameworks-laravel/app/database/database.sqlite
    - php frameworks-laravel/artisan migrate --seed -n --force
    # Laravel 5
    - touch frameworks-l5/storage/testing.sqlite
    - php frameworks-l5/artisan migrate --database=sqlite_testing --force
    # Symfony
    - frameworks-symfony/app/console doctrine:database:create
    - frameworks-symfony/app/console doctrine:schema:create
    - php codecept build -c frameworks-yii-basic/tests
    - php codecept build -c frameworks-phalcon
    - php codecept build -c frameworks-laravel
    - php codecept build -c frameworks-symfony
    - php codecept build -c frameworks-l5
	
    - export PLUGIN_SLUG=$(basename $(pwd))
    - git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
    - git clone --branch="master" https://github.com/inboundnow/cta.git /tmp/wordpress/wp-content/plugins/cta
    - git clone --branch="master" https://github.com/inboundnow/leads.git /tmp/wordpress/wp-content/plugins/leads

    - cd ..
    - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    - php wp-cli.phar --info
    - chmod +x wp-cli.phar
    - sudo mv wp-cli.phar /usr/local/bin/wp

    - mv "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    - cd /tmp/wordpress
    -
     mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    - cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    - ls -l

script: phpunit